version: '3'

services:
  consul:
    image: consul
    container_name: consul-server
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    volumes:
      - consul-volume:/consul/data
    networks:
      - bridge
  
  proxy:
    image: traefik
    container_name: proxy-traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    networks:
      - bridge
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

networks:
  bridge:
    driver: bridge
  hostnet:
    external:
      name: host
  nonet:
    external:
      name: none

volumes:
  consul-volume: